sudo: required
language: go
go:
 - 1.8.3
services:
 - docker
 
install:
  - cd $GOPATH/src/github.com/tjfoc/fabric-ca-gm
  - chmod -R 777 *
  - make lint
  - make format
  - make imports
  #- make rename
  #- make docker
  - cd $GOPATH/src/github.com/tjfoc/fabric-ca-gm/cmd/fabric-ca-client
  - go install
  - cd $GOPATH/src/github.com/tjfoc/fabric-ca-gm/cmd/fabric-ca-server
  - go install
 
notifications:
  email:
    recipients:
      - zhiqiang@tj-fintech.com
      - yanwenze@tj-fintech.com
      - maoxiuze@tj-fintech.com
      - yewei@tj-fintech.com
      
    on_success: never # default: change
    on_failure: never # default: always
  
